import os


root_path = os.getcwd()
asm_csv_path = os.path.join(root_path, 'train_asm.csv')
labels_csv_path = os.path.join(root_path, 'trainLabels.csv')
train_csv_path = os.path.join(root_path, 'asm_files', 'train.csv')
test_csv_path = os.path.join(root_path, 'asm_files', 'test.csv')
proc_train_csv_path = os.path.join(root_path, 'processed_data', 'train_proc.csv')
proc_test_csv_path = os.path.join(root_path, 'processed_data', 'test_proc.csv')
pca_train_csv_path = os.path.join(root_path, 'processed_data', 'pca_train.csv')
pca_test_csv_path = os.path.join(root_path, 'processed_data', 'pca_test.csv')
dumps_path = os.path.join(root_path, 'content', 'cv_scores_dumps')
svm_pycm_dumps_path = os.path.join(root_path, 'content', 'pycm_dumps')
knn_pycm_dumps_path = os.path.join(root_path, 'content', 'pycm_knn_dumps')
LINEAR_SVM_ONE_VS_REST_PATH = os.path.join(os.getcwd(), 'content', 'linear_svm_ovr_trained_model.joblib')
RBF_SVM_ONE_VS_REST_PATH = os.path.join(os.getcwd(), 'content', 'rbf_svm_ovr_trained_model.joblib')
RBF_SVM_PATH = os.path.join(os.getcwd(), 'content', 'rbf_svm_trained_model.joblib')
LINEAR_SVM_PATH = os.path.join(os.getcwd(), 'content', 'linear_svm_trained_model.joblib')
KNN_MODEL_PATH = os.path.join(os.getcwd(), 'content', 'knn_trained_model.joblib')
